# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-04 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTracker',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date_time', models.DateTimeField(null=True)),
                ('end_date_time', models.DateTimeField(null=True)),
                ('topic', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('attendance', models.IntegerField(null=True)),
                ('is_school_community', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Scheduled', 'S'), ('Ongoing', 'O'), ('Done', 'D'), ('Cancelled', 'C')], max_length=20)),
                ('event_type', models.CharField(max_length=30, null=True)),
                ('event_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenteeTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'others')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'others')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='eventtracker',
            name='mentee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one2one_app.MenteeTracker'),
        ),
        migrations.AddField(
            model_name='eventtracker',
            name='mentor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one2one_app.UserProfile'),
        ),
    ]
